version: "3.3"
services:
  vk-yourstickers-db:
    image: postgres:17.0-alpine3.20
    container_name: vk-yourstickers-db
    environment:
      POSTGRES_USER: vk-yourstickers
      POSTGRES_PASSWORD: ReAVECncNy5hpkQG09wk9yFJ6NYTrc0A
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "1320:5432"
    networks:
      - vk-yourstickers_network
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
    command: >
      postgres -c max_connections=1000
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vk-yourstickers -h vk-yourstickers -d postgres -p 5432"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
  vk-yourstickers-cache:
    image: redis:7.4.1-alpine3.20
    container_name: vk-yourstickers-cache
    ports:
      - "1330:6379"
    networks:
      - vk-yourstickers_network
    restart: unless-stopped
  vk-yourstickers-app:
    image: ghcr.io/aejoy/vk-yourstickers:latest
    container_name: vk-yourstickers-app
    depends_on:
      - vk-yourstickers-db
      - vk-yourstickers-cache
    networks:
      - vk-yourstickers_network
    environment:
      ALBUM_ID: ${ALBUM_ID}
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_URL: ${REDIS_URL}
      TOKEN: ${TOKEN}
      USER_TOKEN: ${USER_TOKEN}
    restart: unless-stopped

networks:
  vk-yourstickers_network:
    driver: bridge

volumes:
  pgdata:
    driver: local